### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by notheorem** [castoryan/ORB-SLAM-Android#10]
Finally app launched and initlized SLAM system.
But no featurepoints at all and 0.6 fps.
Any demo video from you somewhere?

Is there something wrong with setting file for my device?
or some thing else?

I am newbee in slam and hope you could show more :)

**Comment by castoryan** [comment]
yeap the system is as slow as you see. I didn't add any visualization on the screen, only running the whole system on background... 
you could add whatever you want base on this code, it should be easy. good luck for you!

**Comment by notheorem** [comment]
thanks  very much ~

**Comment by Pratapabhay** [comment]
Hi @notheorem @castoryan , Everything is working fine, although very slow, that is understandable . But how can you get frames in Monocular SLAM without Bundle adjustment. I have used ORBSLAM2 on Desktop and I just have a question, Are these poses of Keyframes? or are they frames without BA.
Thanks
