### ISSUE TITLE
Error on startup: Couldn't find "libmono.so"

### ISSUE THREAD

**Issue by c-goettert** [castoryan/ORB-SLAM-Android#11]
I am trying to get ORB-SLAM to work on my Nexus5X. I think the device should be compatible with armeabi-v7a.

But when I run the app via Android-Stuio on my phone the App crashes with the following error:
`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.castoryan.orb-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.castoryan.orb-2/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libmono.so"`

I think the error appears when `MyNDK` tries to load local module "mono": ` System.loadLibrary("mono");`.

I don't know why android is searching for "libmono.so" in "arm64"-Folder, since it should be compiling only for a armeabi-v7a right? I am not a specialist here, so maybe its just a small adjustment in Android.mk or Application.mk.

I would very much apprechiate any help on this :)

**Comment by c-goettert** [comment]
Sorry, manually doing NDK-build - as adviced in readme - solved the issue. I really thought Android-Studio would do this on gradle build anyway.

**Comment by eugenelyj** [comment]
@Saiheng  i think the reason why AS reject to do `ndk-build` with run button clicked, is because it spend too much time. Also, what ndk-build doing is to build shared library with native code, which is not the focus  of android development.
