### ISSUE TITLE
OpenCV was not initialised correctly

### ISSUE THREAD

**Issue by Cynica1** [castoryan/ORB-SLAM-Android#14]
Hi, First of all, I apologize for my poor English ability and thank you for making a good SDK.
When I built and ran this project, A popup called "OpenCV Error. OpenCV was not initialised correctly" came up. I installed OpenCV Manager explicitly and tried to reinstall after clearing it.
Can you tell me what to do when this happens?

**Comment by Cynica1** [comment]
Oops, I solved this problem... x_x

**Comment by Pratapabhay** [comment]
Hi @Cynica1 , I am new to android development, could you tell me how did you solve it? I explicitly installed OpenCV manager v3.0.  It is not working for me.
Thanks in Advance
