### ISSUE TITLE
cannot find orb-slam-android.iml

### ISSUE THREAD

**Issue by EricWebsmith** [castoryan/ORB-SLAM-Android#15]
error message:

Cannot load module file '/home/eric/Downloads/ORB-SLAM-Android-master/ORB-SLAM-Android.iml':
File /home/eric/Downloads/ORB-SLAM-Android-master/ORB-SLAM-Android.iml does not exist
Would you like to remove module 'ORB-SLAM-Android' from the project?

I am new to android and i am using the lastest android studio. i got this error. 

thanks.

**Comment by shiweiHou** [comment]
i met the same error, have you solved it?
