### ISSUE TITLE
Before  NDK-build， need to import the opencv as a module into studio, right?

### ISSUE THREAD

**Issue by gogov5** [castoryan/ORB-SLAM-Android#2]
thank you for your code sharing. 
I want to debug it in Android studio,  while,  before building,  I need to import the opencv as a module into studio firstly, right?  

thanks

**Comment by castoryan** [comment]
Yes, the opencv was used as the image interface, so that the data could be sent to the native c++ codes. I think it has been added in the project, right?

From CastorYan

**Comment by castoryan** [comment]
emm, the opencv libraries that used by native codes has been added in the 'jni' folder. You don't need to do anything with it I think…

sorry I am confused a little bit…

From CastorYan
