### ISSUE TITLE
couldn't find "libmono.so"

### ISSUE THREAD

**Issue by augmentedreality01** [castoryan/ORB-SLAM-Android#20]
When i tried to run the App on my Samsung Galaxy S7 i got the following error:
nativeLibraryDirectories=[/data/app/com.example.castoryan.orb-1/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libmono.so"
I'm using Android Studio 3.1.2.

Does anyone have any suggestions?
Thank you in advance!

**Comment by mafanwei** [comment]
How did you solve this problem？

**Comment by ayush7** [comment]
@augmentedreality01 How did you fix the problem. I am having the same issue right now.

**Comment by u-eng** [comment]
Yes please, can you please tell how this problem got resolved?
