### ISSUE TITLE
mono load error

### ISSUE THREAD

**Issue by SimchaShats** [castoryan/ORB-SLAM-Android#6]
Hi I'm getting next Error:
```

Process: com.example.castoryan.orb, PID: 31347
                                                                           java.lang.UnsatisfiedLinkError: Couldn't load mono from loader dalvik.system.PathClassLoader[dexPath=/data/app/com.example.castoryan.orb-2.apk,libraryPath=/data/app-lib/com.example.castoryan.orb-2]: findLibrary returned null
                                                                               at java.lang.Runtime.loadLibrary
```

I'm tried also ndk10 and ndk11, changed path to them in Application.mk like

`
LOCAL_C_INCLUDES += /Users/Simcha/Android/android-ndk-r11c/sources/cxx-stl/llvm-libc++/libcxx/include`

but still have the same error...

**Comment by castoryan** [comment]
have you compiled the library use "ndk-build" ?

**Comment by SimchaShats** [comment]
I'm using Run on Android Studio... (Does AS do compilation automatically?)

**Comment by castoryan** [comment]
certainly not…… you should compile the library in the terminal in AS or in system, first, and then click 'run', these could be found on google.

From CastorYan
