### ISSUE TITLE
Runtime error message on Android 6

### ISSUE THREAD

**Issue by lexvandersluijs** [castoryan/ORB-SLAM-Android#7]
Hi,

Thanks for sharing this interesting work. I've built the native code using the NDK and used Android Studio to build and run the app. However at startup the app shows the message "It seems that you device does not support camera (or it is locked). Application will be closed". The device is a Galaxy Note 4, so the camera is present. In Logcat the following messages are shown: http://pastebin.com/k3Etb03k

Any idea what might be causing this?

BR,
Lex

**Comment by lexvandersluijs** [comment]
Update: setting 'targetSdkVersion' to 19 in build.gradle allows the camera to open.

Then I applied the fix in issue #5, by changing the file-indices around in this line

mn.System(mExternalDirectory + "/ORB2/" + file[0].getName(), mExternalDirectory + "/ORB2/" + file[1].getName(), 0, true, 0, 1);

and it's running :+1:  (after loading the vocabulary, which takes a long time, even on an i7 running a Windows build by the way)

It runs at 1 fps at 1280x720 input resolution, so the next step is to bring this (too high) resolution down a bit.

**Comment by castoryan** [comment]
It is great that you have solved it, have fun with the code!
