### ISSUE TITLE
OpenCV Manager package was not found! Try to install it?

### ISSUE THREAD

**Issue by notheorem** [castoryan/ORB-SLAM-Android#8]
Thanks for the great work you've done.

And I met some problem with it :
After build & run app on device, "OpenCV Manager package was not found! Try to install it?" persists - even though I've installed "OpenCV Manager" from app store.
I think there's some mistake or I missed some thing?
Could you please give some advice ?

I'll follow this project in future, hope to make some thing with map data

**Comment by castoryan** [comment]
yes you should install the opencv first

**Comment by notheorem** [comment]
I tried to install it from appstore and zip from OpenCV webside (2.4.11). Problem persists.
"OpenCV_2.4.11_Manager_2.20_armv7a-neon.apk" is that OK?

**Comment by notheorem** [comment]
by the way, Android 6.0

**Comment by notheorem** [comment]
public static boolean initOpenCV(String Version, final Context AppContext,  
            final LoaderCallbackInterface Callback)  
    {  
        AsyncServiceHelper helper = new AsyncServiceHelper(Version, AppContext, Callback);  
        **Intent intent = new Intent("org.opencv.engine.BIND");  
        intent.setPackage("org.opencv.engine");**  
        if (AppContext.bindService(intent, helper.mServiceConnection, Context.BIND_AUTO_CREATE)) {  
            return true;  
        }  
//        if (AppContext.bindService(new Intent("org.opencv.engine.BIND"),  
//                helper.mServiceConnection, Context.BIND_AUTO_CREATE))  
//        {  
//            return true;  
//        }

**Comment by notheorem** [comment]
for fixing the **java.lang.IllegalArgumentException: Service Intent must be explicit: Intent**
I've made a wrong package name

**Comment by castoryan** [comment]
so is it working now?

**Comment by notheorem** [comment]
Yes it works

**Comment by ShreyashPromact** [comment]
@notheorem 
What should be the package name?
