### ISSUE TITLE
java.lang.IllegalArgumentException: Service Intent must be explicit

### ISSUE THREAD

**Issue by notheorem** [castoryan/ORB-SLAM-Android#9]
Just FYI :

new Intent("org.opencv.engine.BIND")
anonymous intent is not allowed on android 5.0+

fix:

Intent intent = new Intent("org.opencv.engine.BIND");
intent.setPackage(AppContext.getPackageName());

**Comment by Pratapabhay** [comment]
Hi, @notheorem , I am new to android development. Could you tell me where to add these two lines?
Thanks in advance.

**Comment by AlexanderSilvaB** [comment]
Hi @Pratapabhay , you need to add this in line 24 on openCVLibrary2411\java\org.opencv\android\AsyncServiceHelper.java. So, you'll be replacing:

`if (AppContext.bindService(new Intent("org.opencv.engine.BIND"),`

by:

`Intent intent = new Intent("org.opencv.engine.BIND");
 intent.setPackage(AppContext.getPackageName());
 if (AppContext.bindService(intent,`

Hope it helps! :)
